# Converts OPIXray dataset to YOLO format for ultralytics fine-tuning.
#
# Handles this folder structure:
#   OPIXray/
#     train/
#       train_annotation/    <- one .txt per image
#       train_image/         <- .jpg images
#     test/
#       test_annotation/     <- one .txt per image
#       test_image/          <- .jpg images
#
# Annotation format (one or more lines per file):
#   filename.jpg  ClassName  xmin  ymin  xmax  ymax
#   e.g.  009000.jpg Straight_Knife 763 486 840 549
#
# YOLO format output:
#   opixray_yolo/
#     images/
#       train/
#       val/
#     labels/
#       train/
#       val/
#     opixray.yaml


import argparse
import shutil
from pathlib import Path
from PIL import Image

CLASSES = [
    "Folding_Knife",
    "Straight_Knife",
    "Scissor",
    "Utility_Knife",
    "Multi-tool_Knife",
]
CLASS_TO_IDX = {c: i for i, c in enumerate(CLASSES)}


def parse_txt_annotation(ann_path: Path, img_path: Path):
    """
    Parse a plain-text annotation file.

    Format (one line per object):
        filename.jpg  ClassName  xmin  ymin  xmax  ymax

    Returns:
        img_w  : image width  in pixels
        img_h  : image height in pixels
        boxes  : list of dicts {label, xmin, ymin, xmax, ymax}
    """
    # Get image dimensions by opening the image
    with Image.open(img_path) as im:
        img_w, img_h = im.size

    boxes = []
    for line in ann_path.read_text().strip().splitlines():
        line = line.strip()
        if not line:
            continue

        parts = line.split()

        # Expected: filename  class  xmin  ymin  xmax  ymax
        if len(parts) < 6:
            continue

        # parts[0] is the filename — skip it
        label = parts[1]
        if label not in CLASS_TO_IDX:
            continue

        try:
            xmin = float(parts[2])
            ymin = float(parts[3])
            xmax = float(parts[4])
            ymax = float(parts[5])
        except ValueError:
            continue

        boxes.append({
            "label": label,
            "xmin": xmin,
            "ymin": ymin,
            "xmax": xmax,
            "ymax": ymax,
        })

    return img_w, img_h, boxes


def voc_to_yolo(xmin, ymin, xmax, ymax, img_w, img_h):
    """Convert pixel coords [xmin,ymin,xmax,ymax] to YOLO [cx,cy,w,h] (0-1)."""
    cx = (xmin + xmax) / 2.0 / img_w
    cy = (ymin + ymax) / 2.0 / img_h
    w  = (xmax - xmin) / img_w
    h  = (ymax - ymin) / img_h
    return cx, cy, w, h


def write_yolo_label(label_path: Path, img_w: int, img_h: int, boxes: list):
    """Write a YOLO format .txt annotation file."""
    lines = []
    for b in boxes:
        cx, cy, w, h = voc_to_yolo(
            b["xmin"], b["ymin"], b["xmax"], b["ymax"], img_w, img_h
        )
        idx = CLASS_TO_IDX[b["label"]]
        lines.append(f"{idx} {cx:.6f} {cy:.6f} {w:.6f} {h:.6f}")
    label_path.write_text("\n".join(lines))


def write_yaml(dst: Path):
    """Write the ultralytics dataset YAML config file."""
    content = f"""# OPIXray dataset — generated by prepare_opixray.py
path: {dst.resolve()}
train: images/train
val:   images/val

nc: {len(CLASSES)}
names: {CLASSES}
"""
    yaml_path = dst / "opixray.yaml"
    yaml_path.write_text(content)
    print(f"Wrote dataset config : {yaml_path}")


def process_split(
    img_dir: Path,
    ann_dir: Path,
    out_img_dir: Path,
    out_lbl_dir: Path,
    split_name: str,
) -> tuple[int, int]:
    """
    Process one split (train or val).

    Copies images and writes YOLO label files.

    Returns:
        n_images : number of images processed
        n_boxes  : total bounding boxes written
    """
    if not img_dir.exists():
        raise FileNotFoundError(
            f"Image folder not found:\n  {img_dir}\n"
            f"Please check your --src path."
        )
    if not ann_dir.exists():
        raise FileNotFoundError(
            f"Annotation folder not found:\n  {ann_dir}\n"
            f"Please check your --src path."
        )

    # Match each image to its annotation file (same stem, .txt extension)
    pairs = sorted([
        (p, ann_dir / (p.stem + ".txt"))
        for p in img_dir.glob("*.jpg")
        if (ann_dir / (p.stem + ".txt")).exists()
    ])

    if not pairs:
        raise RuntimeError(
            f"No matched image/.txt pairs found.\n"
            f"  Images      : {img_dir}\n"
            f"  Annotations : {ann_dir}\n"
            f"Check that annotation filenames match image filenames "
            f"(e.g. 009000.jpg -> 009000.txt)."
        )

    print(f"Processing {split_name}: {len(pairs)} images ...")

    n_boxes = 0
    for img_path, ann_path in pairs:
        # Copy image
        shutil.copy2(img_path, out_img_dir / img_path.name)

        # Parse annotation and write YOLO label
        img_w, img_h, boxes = parse_txt_annotation(ann_path, img_path)
        write_yolo_label(
            out_lbl_dir / (img_path.stem + ".txt"),
            img_w, img_h, boxes,
        )
        n_boxes += len(boxes)

    return len(pairs), n_boxes


def prepare(src: str, dst: str):
    src_path = Path(src)
    dst_path = Path(dst)

    # Source paths matching your folder structure
    train_img_dir = src_path / "train" / "train_image"
    train_ann_dir = src_path / "train" / "train_annotation"
    test_img_dir  = src_path / "test"  / "test_image"
    test_ann_dir  = src_path / "test"  / "test_annotation"

    # Output paths
    out_train_img = dst_path / "images" / "train"
    out_train_lbl = dst_path / "labels" / "train"
    out_val_img   = dst_path / "images" / "val"
    out_val_lbl   = dst_path / "labels" / "val"

    for d in [out_train_img, out_train_lbl, out_val_img, out_val_lbl]:
        d.mkdir(parents=True, exist_ok=True)

    # Process both splits
    n_train, train_boxes = process_split(
        train_img_dir, train_ann_dir,
        out_train_img, out_train_lbl,
        "train",
    )
    n_val, val_boxes = process_split(
        test_img_dir, test_ann_dir,
        out_val_img, out_val_lbl,
        "val (from test split)",
    )

    print(f"\nDone.")
    print(f"  Train : {n_train} images  |  {train_boxes} boxes")
    print(f"  Val   : {n_val} images  |  {val_boxes} boxes")

    write_yaml(dst_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Prepare OPIXray for YOLOv12 fine-tuning"
    )
    parser.add_argument(
        "--src", required=True,
        help="Path to OPIXray root folder"
    )
    parser.add_argument(
        "--dst", required=True,
        help="Output folder for YOLO-format dataset"
    )
    args = parser.parse_args()
    prepare(args.src, args.dst)